* これなに
  投稿ボックスに入力された内容をbeatmaniaの譜面に変換するmikutterプラグインです.

* 基本の使い方
  投稿ボックスに文字が入っている状態で使うと変換されます.
  実際の変換結果を見るとより使い方がわかりやすいと思います.

  "1", "2",.. "7"を対応する鍵盤の入力とみなします.

  "s"はスクラッチの入力とみなします.

  半角スペースで区切ると譜面を連続させることができます.
  入力した順番が鍵盤を押す順番になります.

  "1", "2",.. "7", および"-"(半角スペースで区切られた最初の要素のみ)以外の文字は無視されます.
  無視される文字を使って譜面に音符のない部分を作ることができます.

* オプション
  半角スペースで区切られた最初の要素に"-"を含む場合,この要素をオプションの入力であるとみなします.
  現在,次のオプションが実装されています."-2"以外の複数のオプションにとれる表記がある場合は,どれか1つだけが有効です.
  各オプションについての解説はここではしません.

  ・ -2 ; (2P側)
      (実際の入力例 : "-2 s147 26 35")

  ・ -r ; RANDOM
      (実際の入力例 : "-r s1 2 3 4 5 6 s7")

  ・ -sr ; S-RANDOM
      (実際の入力例 : "-s 15 3 26 4 37 5 26 4")

  ・ -rr ; R-RANDOM
      (実際の入力例 : "-2rr 7 6 5 4 3 2 1")

  ・ -m ; MIRROR
      (実際の入力例 : "-m 14 25 36 47")

  ・ -scr ; ALL-SCR
      (実際の入力例 : "-2scr s135 246 357 246 s135")

* その他
  変換結果が140字を超える場合には,
  "ノートを処理する順番で"最初の140字を投稿ボックスに入力します.
  一番上の行は結果がおかしくなります.

  1ツイート最大140字という制約はテキストで譜面を表現するためには大きな制約となっています.
  より実用性を高めるために今後連投機能などを実装したいと考えています.

  チャージノートやバックスピンスクラッチについては,一般的なフォントに
  これらに対応できそうな文字が含まれていない関係で実装が困難となっています.
  今のところ対応の予定はありません.

* その他
  フォントによってはきれいな表示が得られない場合がありますが仕様です.

